version: '3'

services:
  pre_run:
    build: .
    image: app
    command: python /manage.py migrate
    volumes:
    - .:/code

  web:
    build: .
    command: python /manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - pre_run
