# Generated by Django 2.2.6 on 2019-11-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_auto_20191103_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
