# Generated by Django 2.2.6 on 2019-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0008_auto_20191103_1314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image", name="like_count", field=models.IntegerField(default=0),
        ),
    ]
