# Generated by Django 2.2.6 on 2019-11-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_auto_20191104_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image", name="caption", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="image", name="tags", field=models.TextField(blank=True),
        ),
    ]
