# Generated by Django 2.2.6 on 2019-11-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo',
            new_name='image',
        ),
    ]
